# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(db_column='商品名称', max_length=20)),
                ('gcount', models.IntegerField(db_column='商品数量', default=0)),
                ('gprice', models.DecimalField(db_column='商品价格', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'good',
            },
        ),
    ]
