# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='gprice',
            field=models.DecimalField(db_column='商品价格', decimal_places=2, default=0, max_digits=6),
        ),
    ]
